SELECT *, '1' as Workout FROM {{ref("DP_JF_SUPERSAPIENS_GLUCOSE_WORKOUT1")}}
UNION ALL
SELECT *, '2' as Workout FROM {{ref("DP_JF_SUPERSAPIENS_GLUCOSE_WORKOUT2")}}
UNION ALL
SELECT *, '3' as Workout FROM {{ref("DP_JF_SUPERSAPIENS_GLUCOSE_WORKOUT3")}}